#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="projet")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Définitions de méthodes d'extensibilité
    partial void OnCreated();
    partial void InsertTable_patient(Table_patient instance);
    partial void UpdateTable_patient(Table_patient instance);
    partial void DeleteTable_patient(Table_patient instance);
    partial void InsertRDV(RDV instance);
    partial void UpdateRDV(RDV instance);
    partial void DeleteRDV(RDV instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Projet.Properties.Settings.Default.projetConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Table_patient> Table_patient
		{
			get
			{
				return this.GetTable<Table_patient>();
			}
		}
		
		public System.Data.Linq.Table<RDV> RDV
		{
			get
			{
				return this.GetTable<RDV>();
			}
		}
		
		public System.Data.Linq.Table<login> login
		{
			get
			{
				return this.GetTable<login>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_patient")]
	public partial class Table_patient : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _num_dossier;
		
		private string _num_sante;
		
		private string _prenom;
		
		private string _nom;
		
		private string _cin;
		
		private string _email;
		
		private string _adresse;
		
		private System.Nullable<System.DateTime> _date_naissance;
		
		private string _lieu_naissance;
		
		private string _tel;
		
		private string _tel_urgence;
		
		private string _sexe;
		
		private string _description;
		
		private string _groupe_sanguin;
		
		private string _situation_familiale;
		
		private string _assurance;
		
		private EntitySet<RDV> _RDV;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onnum_dossierChanging(string value);
    partial void Onnum_dossierChanged();
    partial void Onnum_santeChanging(string value);
    partial void Onnum_santeChanged();
    partial void OnprenomChanging(string value);
    partial void OnprenomChanged();
    partial void OnnomChanging(string value);
    partial void OnnomChanged();
    partial void OncinChanging(string value);
    partial void OncinChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnadresseChanging(string value);
    partial void OnadresseChanged();
    partial void Ondate_naissanceChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_naissanceChanged();
    partial void Onlieu_naissanceChanging(string value);
    partial void Onlieu_naissanceChanged();
    partial void OntelChanging(string value);
    partial void OntelChanged();
    partial void Ontel_urgenceChanging(string value);
    partial void Ontel_urgenceChanged();
    partial void OnsexeChanging(string value);
    partial void OnsexeChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void Ongroupe_sanguinChanging(string value);
    partial void Ongroupe_sanguinChanged();
    partial void Onsituation_familialeChanging(string value);
    partial void Onsituation_familialeChanged();
    partial void OnassuranceChanging(string value);
    partial void OnassuranceChanged();
    #endregion
		
		public Table_patient()
		{
			this._RDV = new EntitySet<RDV>(new Action<RDV>(this.attach_RDV), new Action<RDV>(this.detach_RDV));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_num_dossier", DbType="VarChar(20)")]
		public string num_dossier
		{
			get
			{
				return this._num_dossier;
			}
			set
			{
				if ((this._num_dossier != value))
				{
					this.Onnum_dossierChanging(value);
					this.SendPropertyChanging();
					this._num_dossier = value;
					this.SendPropertyChanged("num_dossier");
					this.Onnum_dossierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_num_sante", DbType="VarChar(20)")]
		public string num_sante
		{
			get
			{
				return this._num_sante;
			}
			set
			{
				if ((this._num_sante != value))
				{
					this.Onnum_santeChanging(value);
					this.SendPropertyChanging();
					this._num_sante = value;
					this.SendPropertyChanged("num_sante");
					this.Onnum_santeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prenom", DbType="Char(20)")]
		public string prenom
		{
			get
			{
				return this._prenom;
			}
			set
			{
				if ((this._prenom != value))
				{
					this.OnprenomChanging(value);
					this.SendPropertyChanging();
					this._prenom = value;
					this.SendPropertyChanged("prenom");
					this.OnprenomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom", DbType="Char(20)")]
		public string nom
		{
			get
			{
				return this._nom;
			}
			set
			{
				if ((this._nom != value))
				{
					this.OnnomChanging(value);
					this.SendPropertyChanging();
					this._nom = value;
					this.SendPropertyChanged("nom");
					this.OnnomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cin", DbType="VarChar(10)")]
		public string cin
		{
			get
			{
				return this._cin;
			}
			set
			{
				if ((this._cin != value))
				{
					this.OncinChanging(value);
					this.SendPropertyChanging();
					this._cin = value;
					this.SendPropertyChanged("cin");
					this.OncinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(20)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adresse", DbType="VarChar(50)")]
		public string adresse
		{
			get
			{
				return this._adresse;
			}
			set
			{
				if ((this._adresse != value))
				{
					this.OnadresseChanging(value);
					this.SendPropertyChanging();
					this._adresse = value;
					this.SendPropertyChanged("adresse");
					this.OnadresseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_naissance", DbType="Date")]
		public System.Nullable<System.DateTime> date_naissance
		{
			get
			{
				return this._date_naissance;
			}
			set
			{
				if ((this._date_naissance != value))
				{
					this.Ondate_naissanceChanging(value);
					this.SendPropertyChanging();
					this._date_naissance = value;
					this.SendPropertyChanged("date_naissance");
					this.Ondate_naissanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lieu_naissance", DbType="Char(20)")]
		public string lieu_naissance
		{
			get
			{
				return this._lieu_naissance;
			}
			set
			{
				if ((this._lieu_naissance != value))
				{
					this.Onlieu_naissanceChanging(value);
					this.SendPropertyChanging();
					this._lieu_naissance = value;
					this.SendPropertyChanged("lieu_naissance");
					this.Onlieu_naissanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel", DbType="Char(20)")]
		public string tel
		{
			get
			{
				return this._tel;
			}
			set
			{
				if ((this._tel != value))
				{
					this.OntelChanging(value);
					this.SendPropertyChanging();
					this._tel = value;
					this.SendPropertyChanged("tel");
					this.OntelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel_urgence", DbType="Char(20)")]
		public string tel_urgence
		{
			get
			{
				return this._tel_urgence;
			}
			set
			{
				if ((this._tel_urgence != value))
				{
					this.Ontel_urgenceChanging(value);
					this.SendPropertyChanging();
					this._tel_urgence = value;
					this.SendPropertyChanged("tel_urgence");
					this.Ontel_urgenceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sexe", DbType="Char(10)")]
		public string sexe
		{
			get
			{
				return this._sexe;
			}
			set
			{
				if ((this._sexe != value))
				{
					this.OnsexeChanging(value);
					this.SendPropertyChanging();
					this._sexe = value;
					this.SendPropertyChanged("sexe");
					this.OnsexeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(90)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_groupe_sanguin", DbType="VarChar(5)")]
		public string groupe_sanguin
		{
			get
			{
				return this._groupe_sanguin;
			}
			set
			{
				if ((this._groupe_sanguin != value))
				{
					this.Ongroupe_sanguinChanging(value);
					this.SendPropertyChanging();
					this._groupe_sanguin = value;
					this.SendPropertyChanged("groupe_sanguin");
					this.Ongroupe_sanguinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_situation_familiale", DbType="Char(10)")]
		public string situation_familiale
		{
			get
			{
				return this._situation_familiale;
			}
			set
			{
				if ((this._situation_familiale != value))
				{
					this.Onsituation_familialeChanging(value);
					this.SendPropertyChanging();
					this._situation_familiale = value;
					this.SendPropertyChanged("situation_familiale");
					this.Onsituation_familialeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_assurance", DbType="VarChar(20)")]
		public string assurance
		{
			get
			{
				return this._assurance;
			}
			set
			{
				if ((this._assurance != value))
				{
					this.OnassuranceChanging(value);
					this.SendPropertyChanging();
					this._assurance = value;
					this.SendPropertyChanged("assurance");
					this.OnassuranceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_patient_RDV", Storage="_RDV", ThisKey="id", OtherKey="id_patient")]
		public EntitySet<RDV> RDV
		{
			get
			{
				return this._RDV;
			}
			set
			{
				this._RDV.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_RDV(RDV entity)
		{
			this.SendPropertyChanging();
			entity.Table_patient = this;
		}
		
		private void detach_RDV(RDV entity)
		{
			this.SendPropertyChanging();
			entity.Table_patient = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RDV")]
	public partial class RDV : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _id_patient;
		
		private string _nom_patient;
		
		private string _prenom_patient;
		
		private System.DateTime _jour;
		
		private string _heure;
		
		private string _description;
		
		private string _statut;
		
		private EntityRef<Table_patient> _Table_patient;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onid_patientChanging(System.Nullable<int> value);
    partial void Onid_patientChanged();
    partial void Onnom_patientChanging(string value);
    partial void Onnom_patientChanged();
    partial void Onprenom_patientChanging(string value);
    partial void Onprenom_patientChanged();
    partial void OnjourChanging(System.DateTime value);
    partial void OnjourChanged();
    partial void OnheureChanging(string value);
    partial void OnheureChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnstatutChanging(string value);
    partial void OnstatutChanged();
    #endregion
		
		public RDV()
		{
			this._Table_patient = default(EntityRef<Table_patient>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_patient", DbType="Int")]
		public System.Nullable<int> id_patient
		{
			get
			{
				return this._id_patient;
			}
			set
			{
				if ((this._id_patient != value))
				{
					if (this._Table_patient.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_patientChanging(value);
					this.SendPropertyChanging();
					this._id_patient = value;
					this.SendPropertyChanged("id_patient");
					this.Onid_patientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom_patient", DbType="Char(20) NOT NULL", CanBeNull=false)]
		public string nom_patient
		{
			get
			{
				return this._nom_patient;
			}
			set
			{
				if ((this._nom_patient != value))
				{
					this.Onnom_patientChanging(value);
					this.SendPropertyChanging();
					this._nom_patient = value;
					this.SendPropertyChanged("nom_patient");
					this.Onnom_patientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prenom_patient", DbType="Char(20) NOT NULL", CanBeNull=false)]
		public string prenom_patient
		{
			get
			{
				return this._prenom_patient;
			}
			set
			{
				if ((this._prenom_patient != value))
				{
					this.Onprenom_patientChanging(value);
					this.SendPropertyChanging();
					this._prenom_patient = value;
					this.SendPropertyChanged("prenom_patient");
					this.Onprenom_patientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jour", DbType="Date NOT NULL")]
		public System.DateTime jour
		{
			get
			{
				return this._jour;
			}
			set
			{
				if ((this._jour != value))
				{
					this.OnjourChanging(value);
					this.SendPropertyChanging();
					this._jour = value;
					this.SendPropertyChanged("jour");
					this.OnjourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_heure", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string heure
		{
			get
			{
				return this._heure;
			}
			set
			{
				if ((this._heure != value))
				{
					this.OnheureChanging(value);
					this.SendPropertyChanging();
					this._heure = value;
					this.SendPropertyChanged("heure");
					this.OnheureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(90)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_statut", DbType="VarChar(10)")]
		public string statut
		{
			get
			{
				return this._statut;
			}
			set
			{
				if ((this._statut != value))
				{
					this.OnstatutChanging(value);
					this.SendPropertyChanging();
					this._statut = value;
					this.SendPropertyChanged("statut");
					this.OnstatutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_patient_RDV", Storage="_Table_patient", ThisKey="id_patient", OtherKey="id", IsForeignKey=true)]
		public Table_patient Table_patient
		{
			get
			{
				return this._Table_patient.Entity;
			}
			set
			{
				Table_patient previousValue = this._Table_patient.Entity;
				if (((previousValue != value) 
							|| (this._Table_patient.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Table_patient.Entity = null;
						previousValue.RDV.Remove(this);
					}
					this._Table_patient.Entity = value;
					if ((value != null))
					{
						value.RDV.Add(this);
						this._id_patient = value.id;
					}
					else
					{
						this._id_patient = default(Nullable<int>);
					}
					this.SendPropertyChanged("Table_patient");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.login")]
	public partial class login
	{
		
		private int _id;
		
		private string _email;
		
		private string _password;
		
		public login()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this._password = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
